frontend:
  url: https://grantfleming.github.io

jwt:
  expiration-time: 43200000 # 12 hours

# hibernate has trouble dropping all tables in the database between tests
# as it seems to be unable to figure out the correct order in which to
# drop the tables. we have to provide a custom sql script to do this by
# just forcefully dropping all objects.
spring:
  jpa:
    properties:
      javax.persistence:
        schema-generation:
          drop-source: script
          drop-script-source: drop-tables.sql
