package co.uk.grantgfleming.SimpleForumBackend.services;

import co.uk.grantgfleming.SimpleForumBackend.data_access.Forum;
import co.uk.grantgfleming.SimpleForumBackend.data_access.Post;

import java.util.List;

/**
 * A service that maintains a list of Posts.
 * <p>
 * The service facilitates access to and operations on the underlying
 * store of posts.
 */
public interface PostService {

    /**
     * Get all {@link Post}s belonging to the {@link Forum} with the given id
     *
     * @param forumId id of the forum for which Posts are requested
     * @return a list of all Posts belonging to the Forum with the given id
     * @throws ForumNotFoundException if no forum exists with the given id
     */
    List<Post> getPostsForForum(Long forumId) throws ForumNotFoundException;

    /**
     * Returns the {@link Post} with the given id
     *
     * @param id of the Post being requested
     * @return the Post with the given id
     * @throws PostNotFoundException if no Post exists with the given id
     */
    Post findPostById(Long id) throws PostNotFoundException;

    /**
     * Adds the given {@link Post} to the underlying store
     *
     * @param post to be added to the store
     * @return the Post (now with a generated id) that has been successfully added to the store
     * @throws InvalidNewPostException if the provided Post already has an id set, this is auto-generated by the
     *                                 store to avoid conflicts
     * @throws ForumNotFoundException  if the provided Post claims to belong to a {@link Forum} that does not exist
     */
    Post addPost(Post post) throws InvalidNewPostException, ForumNotFoundException;

}
