package co.uk.grantgfleming.SimpleForumBackend.forum.services;

import co.uk.grantgfleming.SimpleForumBackend.forum.Forum;
import co.uk.grantgfleming.SimpleForumBackend.forum.ForumRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * The default implementation of {@link ForumService}
 * <p>
 *
 * @see ForumService
 */
@RequiredArgsConstructor
@Service
public class ForumServiceImpl implements ForumService {

    /**
     * The underlying data store from which this service serves
     */
    private final ForumRepository repository;

    @Override
    public List<Forum> allForums() {
        return repository.findAll();
    }

    @Override
    public Forum findForumById(Long id) throws ForumNotFoundException {
        return repository.findById(id).orElseThrow(() -> new ForumNotFoundException(id));
    }

    @Override
    public Forum addForum(Forum forum) throws InvalidNewForumException {
        if (forum.getId() != null) {
            // Id should be generated by the store. Also means that
            // this method will not accidentally overwrite existing
            // Forums
            throw new InvalidNewForumException();
        }

        return repository.save(forum);
    }

    @Override
    public boolean existsById(Long id) {
        return repository.existsById(id);
    }
}
