# This workflow will run all unit and integration tests
# It will also try a cloudfoundry suitable build for sanity checks sake

name: Unit and Integration Tests

on: [pull_request]

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Verify with Maven
        run: mvn -B verify --file pom.xml

      - name: Build with Maven
        run: mvn clean install spring-boot:repackage -P cloudfoundry
